version: '3'

services:
  
  postgres:
    image: postgres:latest
    volumes:
      - postgres-vol:/var/lib/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432

volumes:
  postgres-vol:
