apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: app
          name: app
          resources: {}
          volumeMounts:
            - mountPath: /go/src
              name: app-claim0
      restartPolicy: Always
      volumes:
        - name: app-claim0
          persistentVolumeClaim:
            claimName: app-claim0
status: {}
