apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: control-center
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: control-center
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: control-center
    spec:
      containers:
        - env:
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
          image: confluentinc/cp-control-center:latest
          name: control-center
          ports:
            - containerPort: 9021
          resources: {}
      hostname: control-center
      restartPolicy: Always
status: {}
