apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    io.kompose.service: kafka
status:
  loadBalancer: {}
