apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-topics-generator
  name: kafka-topics-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-topics-generator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/fernando/.asdf/installs/kompose/1.26.1/bin/kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-topics-generator
    spec:
      containers:
        - args:
            - bash
            - -c
            - 'sleep 5 && kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=kafka:9094 --replication-factor=1 --partitions=1 && kafka-topics --create --topic=transaction-confirmation --if-not-exists --bootstrap-server=kafka:9094 --replication-factor=1 --partitions=1 && kafka-topics --create --topic=bank001 --if-not-exists --bootstrap-server=kafka:9094 --replication-factor=1 --partitions=1 && kafka-topics --create --topic=bank002 --if-not-exists --bootstrap-server=kafka:9094 --replication-factor=1 --partitions=1 '
          image: confluentinc/cp-kafka:latest
          name: kafka-topics-generator
          resources: {}
      restartPolicy: Always
status: {}
