/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.sql.SQLException;
import java.sql.Statement;

public class App {

  public class User implements GenericInterface {
    private String id;
    private String username;
    private String password;

    public String getId() {
      return id;
    }

    public String getPassword() {
      return password;
    }

    public String getUsername() {
      return username;
    }

    public void setId(String id) {
      this.id = id;
    }

    public void setPassword(String password) {
      this.password = password;
    }

    public void setUsername(String username) {
      this.username = username;
    }
  }

  public interface GenericInterface {

  }

  public interface CRUDInterface {

    public void create(GenericInterface o);

    public ArrayList<GenericInterface> find(GenericInterface o);

    public GenericInterface findOne(GenericInterface o);

    public void update(GenericInterface o);

    public void delete(GenericInterface o);

  }

  public class UserRepository implements CRUDInterface {

    private User user;

    public UserRepository(User u) {
      this.user.id = u.id;
      this.user.username = u.username;
      this.user.password = u.password;
    }

    @Override
    public void create(GenericInterface o) {
      // TODO Auto-generated method stub

    }

    @Override
    public void update(GenericInterface o) {
      // TODO Auto-generated method stub

    }

    @Override
    public void delete(GenericInterface o) {
      // TODO Auto-generated method stub

    }

    @Override
    public GenericInterface findOne(GenericInterface o) {
      // TODO Auto-generated method stub
      return null;
    }

    @Override
    public ArrayList<GenericInterface> find(GenericInterface o) {
      // TODO Auto-generated method stub
      return null;
    }

  }

  public String getGreeting() {
    return "Hello World!";
  }

  public static Connection getConnection() {

    Connection conn = null;

    try {
      conn = DriverManager.getConnection("jdbc:mysql://localhost/testing?user=test&password=test");

    } catch (Exception e) {
      e.printStackTrace();// TODO: handle exception
    }

    return conn;

  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    Connection conn = null;
    ResultSet rs = null;

    try {
      conn = getConnection();
      Statement stmt = conn.createStatement();
      stmt.execute("show tables like \'user\'");
      ResultSet rsc = stmt.getResultSet();

      // while (rsc.next()) {
      // System.out.println(rsc.getFetchSize());
      // }
      System.out.println(rsc.getFetchSize());

      stmt.execute("create table user ( id varchar(50), username varchar(50), password varchar(50) )");
      stmt.execute("select * from user");
      rs = stmt.getResultSet();
      while (rs.next()) {
        System.out.println(rs.getString("id"));
      }
    } catch (Exception e) {
      e.printStackTrace();
    } finally {

      if (rs != null) {
        try {
          rs.close();
        } catch (SQLException e) {
          e.printStackTrace();
        }
      }

    }

  }
}
