/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dio.bootcamp;

public class App {

  public static void main(String[] args) {
    Funcionario f = new Funcionario();
    Funcionario g = new Gerente();
    Funcionario v = new Vendedor();
    Funcionario x = new Faxineiro();

    System.out.println(f);
    System.out.println(g);
    System.out.println(v);
    System.out.println(x);

    Gerente g2 = (Gerente) new Funcionario();
    Vendedor v2 = (Vendedor) new Funcionario();
    Faxineiro x2 = (Faxineiro) new Funcionario();

    System.out.println(g2);
    System.out.println(v2);
    System.out.println(x2);

  }
}
