/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package remember;

public class App {

  public static void main(String[] args) {

    User u = new User();
    SimpleHasher sp = new SimpleHasher();
    UUIDGenerator uuid = new UUIDGenerator();

    u.setHasher(sp);
    u.setGenerator(uuid);

    u.setUsername("fernando");
    u.setPassword("123");
    u.setEmail("fernando@mail.com");
    u.setId("");

    System.out.println(u.getPassword());
    System.out.println(u.getId());

  }
}
