/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package remember;

public class App {
  public String getGreeting(String greet) {
    return "Hello " + greet;
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting("You"));
  }
}
