version: '3.3'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: 'jenkins/jenkins:lts'
        volumes:
          - jenkins-vol:/var/jenkins_home

volumes:
  jenkins-vol:

